[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
rustflags = [
  # "-C", "linker=flip-link",
  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  "-Z", "trap-unreachable=no",
  "-C", "inline-threshold=5",
  "-C", "no-vectorize-loops",
]
# 
# runner = "elf2uf2-rs -d"
# runner = "probe-run --chip RP2040"
runner = "picotool load -t elf"


[env]
DEFMT_LOG = "debug"
